server:
  port: 53258

spring:
  datasource:
    name: dev
    url: jdbc:mysql://172.16.6.109/jz_metro_revit
    username: root
    password: mysql@303
    driver-class-name: com.mysql.cj.jdbc.Driver #com.mysql.jdbc.Driver
  redis:
    password:
    host: 172.16.6.109 # Redis服务器地址
    port: 6379  # Redis服务器连接端口
    database: 2 # Redis数据库索引（默认为0）
    timeout: 5000 # 连接超时时间（毫秒）
    pool:
      max-active: 8  # 连接池最大连接数（使用负值表示没有限制）
      max-wait: 1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 8  # 连接池中的最大空闲连接
      min-idle: 0  # 连接池中的最小空闲连接

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sccit.invectrl.dbEntitys

